Hw06 pipeline execution
dmirou/otusgopart2 pull request #2
Opened 2020-10-25 12:07 UTC by dmirou

## Домашнее задание №6 «Пайплайн»

### Критерии оценки
- [ ] CI-пайплайн зелёный - 5 баллов
- [ ] Добавлены новые юнит-тесты - до 2 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2020-10-28 17:21 UTC, kulti requested changes
В решение есть 2 ошибки. Предлагаю их поправить.

2020-10-28 17:21 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +		return out
В задании это явно не прописано, но мне кажется пайплайн без стейджей должен просто сквозь себя все пропустить. Т.е. на выходе получится тоже, что было на входе.

Если вы о таком варианте не думали, то, возможно, он вам тоже покажется логичнее. Если текущее поведение кажется логичнее, то тоже ок — можно ничего не переделывать.

2020-10-28 17:21 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +		}
В цикле два селекта с default. Это означает, что селект будет почти всегда выбирать default и просто так тратить время CPU. Правильно тут во втором селекте тоже ждать done (без default).

2020-10-28 17:21 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +				out <- v
Если последующий стейдж уже вышел по done, то эта запись в канал навсегда зависнет.

2020-10-31 10:57 UTC, dmirou commented on hw06_pipeline_execution/pipeline.go
> +		return out
Спасибо, сделал так.

2020-10-31 11:00 UTC, dmirou commented on hw06_pipeline_execution/pipeline.go
> +		}
Понял, спасибо! Исправил. А первый select нужен для кейса когда в done уже отправили, чтобы даже не пытаться работу делать?

2020-10-31 11:00 UTC, dmirou commented on hw06_pipeline_execution/pipeline.go
> +				out <- v
Ага, спасибо. Сделал буферизированным канал.

2020-10-31 12:06 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +				out <- v
Буеризованный канал не поможет. Каждый стейдж работает отдельно. Тот, что пишет в out ждет, когда другой стейдж возьмет значение из out. Буфер лишь отсрочит момент ожидания и снизит вероятность зависания, если закрыли done.

2020-10-31 12:07 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +		}
Можно оставить. Хуже не будет.

2020-10-31 12:08 UTC, kulti requested changes
Буферизованный канал не поможет. Отписал в дискашене детали.

2020-11-05 04:00 UTC, dmirou commented
> Буферизованный канал не поможет. Отписал в дискашене детали. Если есть вопросы, то можно обсудить в слаке.

Хорошо, подумаю, если что напишу в слаке.

2020-11-15 11:25 UTC, dmirou commented on hw06_pipeline_execution/pipeline.go
> +				out <- v
Добавил чтобы runStage возвращал новый done канал, который закрывается после закрытия входящего done канала, чтобы завершать стейджи последовательно.

2020-11-18 10:49 UTC, kulti approved these changes
Теперь решение корректное, хоть и переусложненное. ДЗ принято - 8/10.

2020-11-18 10:49 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +		if done == nil {
Если done == nil, то он никогда не будет готов для чтения, т.е. select никогда не выберет ветку с ним. Можно отдельно этот случай не обрабатывать.

2020-11-18 10:49 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +				out <- v
Хммм... Сложновато получилось, но вроде должно работать. Есть решение сильно проще. Если интересно, можете написать, подскажу, в каком направлении подумать.

2020-11-22 11:36 UTC, dmirou commented on hw06_pipeline_execution/pipeline.go
> +		if done == nil {
Ага, спасибо. Исправил.

2020-11-22 11:48 UTC, merged